// <auto-generated />
namespace FilmTrove.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class merges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merges));
        
        string IMigrationMetadata.Id
        {
            get { return "201305131842022_merges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
