// <auto-generated />
namespace FilmTrove.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class merges2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merges2));
        
        string IMigrationMetadata.Id
        {
            get { return "201305131850090_merges2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
