// <auto-generated />
namespace FilmTrove.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class LastFullUpdateToProviderInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LastFullUpdateToProviderInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201304232309314_LastFullUpdateToProviderInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
