// <auto-generated />
namespace FilmTrove.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class merges3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merges3));
        
        string IMigrationMetadata.Id
        {
            get { return "201305142049224_merges3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
